"""init

Revision ID: 511582927082
Revises: 
Create Date: 2026-06-03 12:14:01.843975
"""
from alembic import op
import sqlalchemy as sa


revision = '511582927082'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cms_strings',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('key', sa.String(length=200), nullable=False),
    sa.Column('lang', sa.String(length=5), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key', 'lang', name='uq_cms_key_lang')
    )
    op.create_index(op.f('ix_cms_strings_key'), 'cms_strings', ['key'], unique=False)
    op.create_table('draft_users',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('contact_type', sa.String(length=20), nullable=False),
    sa.Column('contact_value', sa.String(length=200), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('reminder_sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('converted_user_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_draft_users_contact_value'), 'draft_users', ['contact_value'], unique=False)
    op.create_table('knowledge_base',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('category', sa.Enum('LEGAL', 'PRICING', 'REGIONS', 'FAQ', 'PROCESS', name='knowledgecategory'), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('lang', sa.String(length=5), nullable=False),
    sa.Column('embedding', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_knowledge_base_category'), 'knowledge_base', ['category'], unique=False)
    op.create_index(op.f('ix_knowledge_base_lang'), 'knowledge_base', ['lang'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('ADMIN', 'SELLER', 'BUYER', 'DRAFT', name='userrole'), nullable=False),
    sa.Column('full_name', sa.String(length=200), nullable=True),
    sa.Column('preferred_lang', sa.String(length=5), nullable=False),
    sa.Column('telegram', sa.String(length=100), nullable=True),
    sa.Column('phone', sa.String(length=30), nullable=True),
    sa.Column('whatsapp', sa.String(length=30), nullable=True),
    sa.Column('viber', sa.String(length=30), nullable=True),
    sa.Column('instagram', sa.String(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('is_dual_role', sa.Boolean(), nullable=False),
    sa.Column('verification_token', sa.String(length=100), nullable=True),
    sa.Column('reset_token', sa.String(length=100), nullable=True),
    sa.Column('reset_token_expires', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_active_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_reset_token'), 'users', ['reset_token'], unique=False)
    op.create_index(op.f('ix_users_verification_token'), 'users', ['verification_token'], unique=False)
    op.create_table('assistant_tickets',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('user_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('draft_user_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('question_text', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('NEW', 'IN_PROGRESS', 'CLOSED', name='ticketstatus'), nullable=False),
    sa.Column('admin_response', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['draft_user_id'], ['draft_users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_assistant_tickets_status'), 'assistant_tickets', ['status'], unique=False)
    op.create_index(op.f('ix_assistant_tickets_user_id'), 'assistant_tickets', ['user_id'], unique=False)
    op.create_table('land_for_buy',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('buyer_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('region', sa.String(length=100), nullable=True),
    sa.Column('cities', sa.JSON(), nullable=True),
    sa.Column('area_min_m2', sa.Integer(), nullable=True),
    sa.Column('area_max_m2', sa.Integer(), nullable=True),
    sa.Column('price_min_eur', sa.Integer(), nullable=True),
    sa.Column('price_max_eur', sa.Integer(), nullable=True),
    sa.Column('channels', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['buyer_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_land_for_buy_buyer_id'), 'land_for_buy', ['buyer_id'], unique=False)
    op.create_index(op.f('ix_land_for_buy_is_active'), 'land_for_buy', ['is_active'], unique=False)
    op.create_index(op.f('ix_land_for_buy_region'), 'land_for_buy', ['region'], unique=False)
    op.create_table('land_for_sell',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('seller_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('broj', sa.String(length=50), nullable=True),
    sa.Column('region', sa.String(length=100), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('address', sa.String(length=300), nullable=True),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('lon', sa.Float(), nullable=True),
    sa.Column('area_m2', sa.Integer(), nullable=True),
    sa.Column('price_eur', sa.Integer(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('photos', sa.JSON(), nullable=True),
    sa.Column('contacts', sa.JSON(), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'SOLD', 'SUSPENDED', name='landstatus'), nullable=False),
    sa.Column('admin_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['seller_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_land_for_sell_area_m2'), 'land_for_sell', ['area_m2'], unique=False)
    op.create_index(op.f('ix_land_for_sell_broj'), 'land_for_sell', ['broj'], unique=False)
    op.create_index(op.f('ix_land_for_sell_city'), 'land_for_sell', ['city'], unique=False)
    op.create_index(op.f('ix_land_for_sell_price_eur'), 'land_for_sell', ['price_eur'], unique=False)
    op.create_index(op.f('ix_land_for_sell_region'), 'land_for_sell', ['region'], unique=False)
    op.create_index(op.f('ix_land_for_sell_seller_id'), 'land_for_sell', ['seller_id'], unique=False)
    op.create_index(op.f('ix_land_for_sell_status'), 'land_for_sell', ['status'], unique=False)
    op.create_table('notifications_log',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('recipient_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('type', sa.Enum('MATCH_FOUND', 'NEW_BUYER', 'REMINDER', 'MERGE_SUGGESTION', 'EMAIL_VERIFICATION', 'PASSWORD_RESET', name='notificationtype'), nullable=False),
    sa.Column('channel', sa.Enum('EMAIL', 'TELEGRAM', 'PUSH', name='notificationchannel'), nullable=False),
    sa.Column('subject', sa.String(length=300), nullable=True),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['recipient_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_log_recipient_id'), 'notifications_log', ['recipient_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_notifications_log_recipient_id'), table_name='notifications_log')
    op.drop_table('notifications_log')
    op.drop_index(op.f('ix_land_for_sell_status'), table_name='land_for_sell')
    op.drop_index(op.f('ix_land_for_sell_seller_id'), table_name='land_for_sell')
    op.drop_index(op.f('ix_land_for_sell_region'), table_name='land_for_sell')
    op.drop_index(op.f('ix_land_for_sell_price_eur'), table_name='land_for_sell')
    op.drop_index(op.f('ix_land_for_sell_city'), table_name='land_for_sell')
    op.drop_index(op.f('ix_land_for_sell_broj'), table_name='land_for_sell')
    op.drop_index(op.f('ix_land_for_sell_area_m2'), table_name='land_for_sell')
    op.drop_table('land_for_sell')
    op.drop_index(op.f('ix_land_for_buy_region'), table_name='land_for_buy')
    op.drop_index(op.f('ix_land_for_buy_is_active'), table_name='land_for_buy')
    op.drop_index(op.f('ix_land_for_buy_buyer_id'), table_name='land_for_buy')
    op.drop_table('land_for_buy')
    op.drop_index(op.f('ix_assistant_tickets_user_id'), table_name='assistant_tickets')
    op.drop_index(op.f('ix_assistant_tickets_status'), table_name='assistant_tickets')
    op.drop_table('assistant_tickets')
    op.drop_index(op.f('ix_users_verification_token'), table_name='users')
    op.drop_index(op.f('ix_users_reset_token'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_knowledge_base_lang'), table_name='knowledge_base')
    op.drop_index(op.f('ix_knowledge_base_category'), table_name='knowledge_base')
    op.drop_table('knowledge_base')
    op.drop_index(op.f('ix_draft_users_contact_value'), table_name='draft_users')
    op.drop_table('draft_users')
    op.drop_index(op.f('ix_cms_strings_key'), table_name='cms_strings')
    op.drop_table('cms_strings')
    # ### end Alembic commands ###