"""add phone_otps table and messenger_channel enum

Revision ID: 6c0963c40d7f
Revises: 511582927082
Create Date: 2026-06-25 18:22:41.648070
"""
from alembic import op
import sqlalchemy as sa


revision = '6c0963c40d7f'
down_revision = '511582927082'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('phone_otps',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('phone', sa.String(length=30), nullable=False),
    sa.Column('channel', sa.Enum('WHATSAPP', 'VIBER', 'TELEGRAM', name='messengerchannel'), nullable=False),
    sa.Column('code', sa.String(length=6), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('used', sa.Boolean(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_phone_otps_phone'), 'phone_otps', ['phone'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_phone_otps_phone'), table_name='phone_otps')
    op.drop_table('phone_otps')
    # ### end Alembic commands ###